# Use the official Neo4j 4.4 image as the base image
FROM neo4j:enterprise

# Set the container name
ARG CONTAINER_NAME=neo

# Set environment variables
ENV NEO4J_dbms_security_procedures_unrestricted=apoc.* \
    NEO4J_dbms_security_procedures_allowlist=apoc.* \
    NEO4J_PLUGINS=["apoc"] \
    NEO4J_apoc_import_file_enabled=true \
    NEO4J_server_directories_logs=/data \
    NEO4J_server.memory.pagecache.size=4G \
    NEO4J_server.default_listen_address=0.0.0.0  \
    NEO4J_ACCEPT_LICENSE_AGREEMENT=eval \
    NEO4J_dbms_security_auth__enabled=false

EXPOSE 7474 7473 7687
RUN echo

# Set volumes
VOLUME /plugins
VOLUME /data
VOLUME /import
VOLUME /conf

CMD ["neo4j"]
# ENTRYPOINT [ "echo \"ALTER USER neo4j SET PASSWORD 'neo4j'\" | cypher-shell -a bolt://neo:7687  -u neo4j -p neo4j --database neo4j" ]
