# Use the official Neo4j 4.4 image as the base image
FROM neo4j:4.4

# Set the container name
ARG CONTAINER_NAME=neo

# Set environment variables
ENV NEO4J_dbms_security_procedures_unrestricted=apoc.* \
    NEO4J_dbms_security_procedures_allowlist=apoc.* \
    NEO4JLABS_PLUGINS=["apoc"] \
    NEO4J_apoc_import_file_enabled=true \
    NEO4J_server_directories_logs=/data \
    NEO4J_apoc_import_file_use__neo4j__config=false \
    NEO4J_dbms_memory_pagecache_size=4G \
    NEO4J_dbms_default__listen__address=0.0.0.0 \
    NEO4J_dbms_default__advertised__address=$CONTAINER_NAME \
    NEO4J_dbms_connector_https_advertised__address=0.0.0.0:7473 \
    NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474 \
    NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687 \
    NEO4J_dbms_security_auth__enabled=false

# Expose ports
EXPOSE 7474 7473 7687
RUN echo 

# Set volumes
VOLUME /plugins /data /import

# Start Neo4j server
CMD ["neo4j"]
# ENTRYPOINT [ "echo \"ALTER USER neo4j SET PASSWORD 'neo4j'\" | cypher-shell -a bolt://neo:7687  -u neo4j -p neo4j --database neo4j" ]