name: Debug SSH Connection

on:
  workflow_dispatch: # Manual trigger only for testing

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          debug: true # Enable debug output
          script: |
            whoami
            pwd
            echo "Connection successful! $(whoami)"
